Add sorting to calendar entries in month view
jlawyerorg/j-lawyer-org pull request #1661
Opened 2022-05-24 15:26 UTC by Bentipa

Closes #1589

![image](https://user-images.githubusercontent.com/11789478/170073506-b5da7eea-8a57-4ca9-9895-ea142c291ffa.png)

Events are now sorted in the order Termin -> Frist -> WV

2022-05-24 17:23 UTC, j-dimension requested changes

2022-05-26 08:26 UTC, Bentipa commented on j-lawyer-client/src/de/costache/calendar/ui/DayContentPanel.java
> +            if (o1.getType().getUniqueKey().equals(o2.getType().getUniqueKey())) {
done

2022-05-26 08:26 UTC, Bentipa commented on j-lawyer-client/src/de/costache/calendar/ui/DayContentPanel.java
> +            } else if (o1.getType().getUniqueKey().equals("Termin")) {
done

2022-05-27 21:28 UTC, merged

2022-05-27 23:00 UTC, j-dimension commented
@Bentipa thanks for your contributions!

Related to this PR, I noticed an issue with the tooltips being shown for different events. That is due to the sorting taking place on paint, but then in case of mouse events the events are retrieved by their location based on the unsorted list in 

`private CalendarEvent getEvent(final int x, final int y)`

(there are several of them)
So I added the sorting there as well. Might become an issue for databases with millions of events, but I do not know of such installation yet :-)

2022-05-28 08:37 UTC, Bentipa commented
@j-dimension Ah yeah that makes sense :) 
Maybe the sorting could also already take place earlier, maybe when adding entries?
This would remove the sorting operation from the render / getEvent methods and maybe reduce their execution count.

2022-05-28 10:21 UTC, j-dimension commented
@Bentipa yes, I will look into converting the internal collection into a TreeSet.