added button to delete single pdf pages in documentviewer
jlawyerorg/j-lawyer-org pull request #2587
Opened 2024-09-28 19:06 UTC by iradraconis

implementiert #2586

2024-09-28 22:17 UTC, j-dimension requested changes
Das schaut super aus, danke @iradraconis !

Ich habe noch zwei kleine Wünsche hinterlassen :-)

2024-09-28 22:17 UTC, j-dimension commented on j-lawyer-client/src/com/jdimension/jlawyer/client/editors/documents/viewer/PdfImageScrollingPanel.java
> +    public void removePages(int[] pageIndexes, int par1) {
Parameter par1 wird nicht genutzt und könnte entfernt werden.

2024-09-28 22:17 UTC, j-dimension commented on j-lawyer-client/src/com/jdimension/jlawyer/client/editors/documents/viewer/PdfPageImage.java
> +        int response = JOptionPane.showConfirmDialog(this, "Möchten Sie die Seite wirklich entfernen?", "Bestätigung", JOptionPane.YES_NO_OPTION);
Ich versuche die "Sie" vs. "Du"-Problematik möglichst zu umschiffen. Können wir hier neutral formulieren, bspw. "Soll die Seite wirklich entfernt werden?"

2024-09-29 05:15 UTC, iradraconis commented on j-lawyer-client/src/com/jdimension/jlawyer/client/editors/documents/viewer/PdfImageScrollingPanel.java
> +    public void removePages(int[] pageIndexes, int par1) {
ja hast Recht, wird ja nix gedreht :)

2024-09-29 20:18 UTC, merged