added "send via Thunderbird" button to eMailDialog
jlawyerorg/j-lawyer-org pull request #2602
Opened 2024-10-06 19:57 UTC by iradraconis

Empfänger, Betreff, Mailtext und Anhänge werden übernommen und in Thunderbird geöffnet.
Eine Prüfung des Installationspfads von Thunderbird je nach OS ist integriert. Das müsste noch getestet werden, bei mir unter Linux funktioniert es. 

Vorteile: 
- Mail kann erstellt werden anhand aller Aktendaten und auch mit allen Vorlagen.
- Ingo kann zur Erstellung der Mails genutzt werden.
- Mail kann in Thunderbird signiert und verschlüsselt werden
- weitere Extensions in Thunderbird können genutzt werden (Language Tool z.B.)
- Rückspeicherung kann per TB Erweiterung erfolgen. 

Das "einfache Versenden" einer Datei per Thunderbird ist daneben auch per individuellem Launcher möglich (schon getestet)

2024-10-06 21:21 UTC, j-dimension requested changes

2024-10-06 21:21 UTC, j-dimension commented on j-lawyer-client/src/com/jdimension/jlawyer/client/mail/SendEmailDialog.form
> +                      <Image iconType="3" name="/icons32/mail_forward.png"/>
können wir ein anderes icon dafür verwenden? ich habe eines erstellt und hänge es mit an.
![outgoing_mail_24dp_0E72B5](https://github.com/user-attachments/assets/7126d8d9-fe55-4dca-beab-31149b9959c6)

2024-10-06 21:21 UTC, j-dimension commented on j-lawyer-client/src/com/jdimension/jlawyer/client/mail/SendEmailDialog.java
> +        System.out.println("Thunderbird Command: " + String.join(" ", command));
hier bitte log.info nutzen, sonst landet das nicht im client log

2024-10-06 21:21 UTC, j-dimension commented on j-lawyer-client/src/com/jdimension/jlawyer/client/mail/SendEmailDialog.java
> +            e.printStackTrace();
hier bitte log.error nutzen, sonst landet das nicht im client log

2024-10-06 21:21 UTC, j-dimension commented on j-lawyer-client/src/com/jdimension/jlawyer/client/mail/SendEmailDialog.java
> +        if (os.contains("win")) {
es gibt eine Klasse SystemUtils, die hat Methoden für isMac, isLinux, isWindows. Es wäre besser diese zu verwenden, sodass bei einer Änderung am Betriebssystemcheck nur eine Stelle anzupassen ist.

2024-10-06 21:21 UTC, j-dimension commented on j-lawyer-client/src/com/jdimension/jlawyer/client/mail/SendEmailDialog.java
> +        return null; // Unbekanntes Betriebssystem
hier ein log.error, damit man als supporter erkennen kann, dass ein unbekanntes betriebssystem genutzt wird

2024-10-06 21:21 UTC, j-dimension commented on j-lawyer-client/src/com/jdimension/jlawyer/client/mail/SendEmailDialog.java
> +            e.printStackTrace();
log.error

2024-10-06 21:21 UTC, j-dimension commented on j-lawyer-client/src/com/jdimension/jlawyer/client/mail/SendEmailDialog.java
> +            e.printStackTrace();
log.error

2024-10-07 04:19 UTC, iradraconis commented on j-lawyer-client/src/com/jdimension/jlawyer/client/mail/SendEmailDialog.form
> +                      <Image iconType="3" name="/icons32/mail_forward.png"/>
erledigt

2024-10-07 18:52 UTC, iradraconis commented
Empfänger ist erforderlich, da ansonsten die in Thunderbird geöffnete Mail komplett leer ist.

2024-10-07 19:29 UTC, j-dimension commented
Klasse, herzlichen Dank für die Korrekturen, @iradraconis !

2024-10-07 19:30 UTC, merged

2024-10-07 21:32 UTC, j-dimension commented
@iradraconis lässt sich evtl. auch das "from" übergeben? Ich nutze unterschiedliche Mailaccounts, habe im Versanddialog ein Dropdown. Wäre cool wenn das aktuell gewählte Postfach übergeben werden könnte.

2024-10-07 21:32 UTC, j-dimension commented
Test Linux hier grundsätzlich erfolgreich.

2024-10-08 04:06 UTC, iradraconis commented
Das ist grundsätzlich möglich

2024-10-30 18:27 UTC, librelegal commented
Funktioniert unter Linux und Windows, wunderbar. Danke