Feat/add dictation to notes
jlawyerorg/j-lawyer-org pull request #2613
Opened 2024-10-16 21:02 UTC by iradraconis

Eine Sache, die noch zu tun wäre:
Wenn der Anwender, bevor er in einer Notiz die Transkription startet, nicht vorher den Cursor setzt, wird die Aufnahme VOR den Table gesetzt. Das soll ja nicht so sein. Eine Logik fehlt, die zuverlässig prüft, dass die Transkription immer nach dem Table und dem hr tag erfolgen soll, aber dann trotzem an der caret position eingefügt wird.

2024-10-19 21:24 UTC, j-dimension commented
@iradraconis soll ich das trotz des offenen Punktes übernehmen? Für die angesprochene Logik habe ich gerade keine Lösung.

2024-10-19 21:28 UTC, j-dimension requested changes

2024-10-19 21:28 UTC, j-dimension commented on j-lawyer-client/src/com/jdimension/jlawyer/client/editors/documents/viewer/HtmlPanel.java
> +    public List<InputData> getInputs(AiCapability c) {
@iradraconis kannst Du das mal auskommentieren / die Methode eine leere Liste ausgeben lassen? Für die Transkription wird ja der aktuelle Notiztext nicht benötigt. Mit dem Code unten würde der Notiztext immer an Ingo übertragen werden.

2024-10-19 21:28 UTC, j-dimension commented on j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/AddNoteDialog.java
> +        EditorImplementation ed = (EditorImplementation) this.htmlEditorPanel1.getComponent(0);
wie oben - ich meine dass eine leere Liste als return hier ausreichen würde

2024-10-20 18:51 UTC, iradraconis commented
> @iradraconis soll ich das trotz des offenen Punktes übernehmen? Für die angesprochene Logik habe ich gerade keine Lösung.

Habe die Änderungen vorgenommen. 

Mir reicht das so. Ich habe für das einfache htmlPanel auch weiterhin keine Lösung gefunden. So muss halt mit der Maus einmal reingeklickt werden, um den Cursor zu setzen. Vielleicht kann man das später noch mal anfassen.

Es würde mich sehr freuen, wenn du das mergen könntest.

2024-10-20 18:54 UTC, merged